# deployment of 3 nodes of the server
version: '3.8'

services:
  node-1:
    container_name: node-1
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/go/src/doq
    ports:
      - "9000"
      - "8000:8000"
      - "10000:10000"
    command: [
      "go",
      "run",
      "main.go",
      "--storage.data_dir",
      "/usr/local/doq/data",
      "--cluster.node_id",
      "node-1",
      "--http.port",
      "8000",
      "--raft.address",
      "node-1:9000",
      "--grpc.address",
      "node-1:10000"
    ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/readyz"]
      interval: 10s
      timeout: 10s
      retries: 5

  node-2:
    container_name: node-2
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/go/src/doq
    ports:
      - "9000"
      - "8001:8000"
      - "10001:10000"
    command: [
      "go",
      "run",
      "main.go",
      "--storage.data_dir",
      "/usr/local/doq/data",
      "--cluster.node_id",
      "node-2",
      "--http.port",
      "8000",
      "--raft.address",
      "node-2:9000",
      "--cluster.join_addr",
      "node-1:8000",
      "--grpc.address",
      "node-2:10000"
    ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/readyz"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      node-1:
        condition: service_healthy

  node-3:
    container_name: node-3
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/go/src/doq
    ports:
      - "9000"
      - "8002:8000"
      - "10002:10000"
    command: [
      "go",
      "run",
      "main.go",
      "--storage.data_dir",
      "/usr/local/doq/data",
      "--cluster.node_id",
      "node-3",
      "--http.port",
      "8000",
      "--raft.address",
      "node-3:9000",
      "--cluster.join_addr",
      "node-1:8000",
      "--grpc.address",
      "node-3:10000"
    ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/readyz"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      node-1:
        condition: service_healthy

  # python:
  #   container_name: shell
  #   build:
  #     context: python
  #     dockerfile: Dockerfile
