# deployment of 3 nodes of the server
version: '3.8'

services:
  doq:
    container_name: doq
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/go/src/doq
    ports:
      - "9000"
      - "8000:8000"
      - "10000:10000"
    command: [
      "go",
      "run",
      "main.go",
      "--storage.data_dir",
      "/usr/local/doq/data",
      "--cluster.node_id",
      "doq",
      "--http.port",
      "8000",
      "--raft.address",
      "doq:9000",
      "--grpc.address",
      "doq:10000"
    ]
  python:
    container_name: python
    build:
      context: python
      dockerfile: Dockerfile
    environment:
      - BASE_URL=http://doq:8000
