# deployment of 3 nodes of the server
version: '3.8'

services:
  node-1:
    container_name: node-1
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/go/src/doq
    ports:
      - "9000"
      - "8001:8000"
    command: [
      "go",
      "run",
      "main.go",
      "--storage.data_dir",
      "/usr/local/doq/data",
      "--cluster.node_id",
      "node-1",
      "--http.port",
      "8000",
      "--raft.address",
      "node-1:9000",
    ]
  node-2:
    container_name: node-2
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/go/src/doq
    ports:
      - "9000"
      - "8002:8000"
    command: [
      "go",
      "run",
      "main.go",
      "--storage.data_dir",
      "/usr/local/doq/data",
      "--cluster.node_id",
      "node-2",
      "--http.port",
      "8000",
      "--raft.address",
      "node-2:9000",
      "--cluster.join_addr",
      "node-1:8000"
    ]
  node-3:
    container_name: node-3
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/go/src/doq
    ports:
      - "9000"
      - "8003:8000"
    command: [
      "go",
      "run",
      "main.go",
      "--storage.data_dir",
      "/usr/local/doq/data",
      "--cluster.node_id",
      "node-3",
      "--http.port",
      "8000",
      "--raft.address",
      "node-3:9000",
      "--cluster.join_addr",
      "node-1:8000"
    ]
  python:
    container_name: shell
    build:
      context: python
      dockerfile: Dockerfile
