apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: doq-internal
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: doq
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
