apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: doq-endpointslice-creator
rules:
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
