apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: doq-endpointslice-creator-binding
subjects:
  - kind: ServiceAccount
    name: doq
    namespace: default
roleRef:
  kind: Role
  name: doq-endpointslice-creator
  apiGroup: rbac.authorization.k8s.io
