apiVersion: v1
kind: Service
metadata:
  name: doq
  labels:
    app: doq
spec:
  clusterIP: None
  selector:
    app: doq
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: grpc
      port: 10000
      targetPort: 10000
      protocol: TCP
